### ISSUE TITLE
using this repository

### ISSUE THREAD

**Issue by moorlag** [Piersoncollege/html#10]
@lesander 
@jessevdp
Does this repository reflect the best usage Github?

**Comment by lesander** [comment]
What do you mean @moorlag?

**Comment by moorlag** [comment]
@lesander do you use the tab 'projects'? Goal for this repository is to reflect the best use case of Github.

**Comment by lesander** [comment]
@moorlag this repository does not have any project(s)? I honestly think that when you're looking for best-use cases of Git(Hub) and open-source project management, the best place to look is at popular open-source projects on GitHub. https://github.com/explore

**Comment by jessevdp** [comment]
Agreed.

What about this repository?
https://github.com/primer/primer

Primer is the Design System that powers GitHub. It's maintained by one of GitHubs teams themselves.
http://primercss.io/
