### ISSUE TITLE
Adding visuals to manual

### ISSUE THREAD

**Issue by moorlag** [Piersoncollege/html#12]
Adding more visual clues how to upload a website to Github Pages. 
Perhaps a video explaining the proces.

**Comment by jessevdp** [comment]
Is the standard guide by GitHub not clear enough? https://pages.github.com/

**Comment by moorlag** [comment]
Guide isn't clear when not using the client software.


Met vriendelijke groet / with kind regards,

Ramon Moorlag
about.me/moorlag
