### ISSUE TITLE
Broken link?

### ISSUE THREAD

**Issue by skillzzjesse** [Piersoncollege/html#3]
[moorlag.github.io][1] returns `404`.

The repository is no longer owned by user [moorlag][2] (since it was transferred to the organisation [Piersoncollege][3]).

**Fix:** Create a new branch  called `gh-pages`  and push everything towards this branch. 
Note that the new url will be `piersoncollege.github.io/moorlag.github.io` since `<owner>.github.io/<repository>`

I recommend the repository name is changed :wink:

**Usefull links**
[pages.github.com](https://pages.github.com/)
[gh-pages documentation](https://help.github.com/categories/github-pages-basics/)

[1]: https://moorlag.github.io 
[2]: https://github.com/moorlag
[3]: https://github.com/Piersoncollege

**Comment by skillzzjesse** [comment]
Have fun fixin it :wink:

**Comment by moorlag** [comment]
:octocat: to the rescue

**Comment by moorlag** [comment]
http://piersoncollege.github.io/html/ back online.

**Comment by skillzzjesse** [comment]
Make sure to update the README aswell. :wink:

**Comment by moorlag** [comment]
Solved.

**Comment by moorlag** [comment]
updated!
